# https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tiny.desk5777@fastmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-prod
    solvers:
      - http01:
          ingress:
            class: public
