version: '3'

services:
  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    network_mode: "host"
