apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'repeti2.com' ) {
        rewrite ^ https://www.repeti2.com$request_uri permanent;
      }
spec:
  tls:
    - hosts:
        - repeti2.com
        - www.repeti2.com
      secretName: tls-secret-prod
  rules:
    - host: repeti2.com
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: headcrab-service
                port:
                  number: 80
    - host: www.repeti2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headcrab-service
                port:
                  number: 80
