apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - boigs.uk.to
    secretName: tls-secret-prod
  rules:
  - host: boigs.uk.to
    http:
      paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: frontend-service
              port:
                number: 80
        - path: /clown
          pathType: Prefix
          backend:
            service:
              name: clown-service
              port:
                number: 80
