name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Deploy Certificate Manager
      run: microk8s kubectl apply -f cert-manager.yaml
    - name: Deploy Ingress
      run: microk8s kubectl apply -f ingress.yaml
